config/routes.rb
Rails.application.routes.draw do
 
  resources :instudios do 
  resources :moodboards, only: :index 
  resources :addons, only: :index 
  resources :calendars, only: [ :new, :create ]
  end

  resources :calendars
  resources :products
  resources :moodboards, only: [ :show, :edit, :update, :destroy, :index ]
  resources :addons, only: [ :show, :edit, :update, :destroy, :index ]

  resources :products do 
    resources :moodboards, only: [ :new, :create ]
    resources :addons, only: [ :new, :create, :index ]

  end

  resources :clients
  
  devise_for :users
  root to: "pages#home"

  resources :categories do 
    resources :backgrounds, only: [ :new, :create, :index ]
    resources :angles, only: [ :new, :create, :index ]
    resources :sizes, only: [ :new, :create, :index ]
   end
  
   resources :angles, only: [ :show, :edit, :update, :destroy ]
   resources :backgrounds, only: [ :show, :edit, :update, :destroy ]
   resources :sizes, only: [ :show, :edit, :update, :destroy ]
   resources :briefings, only: [ :show, :edit, :update, :destroy ]
   resources :deliveries, only: [ :show, :edit, :update, :destroy ]


   get '/profile', to: 'pages#profile'
   get '/new', to: 'pages#new'
   get '/dashboard', to: 'pages#dashboard'
   get '/dashboard_products', to: 'pages#dashboard_products'
   get '/dashboard_instudio', to: 'pages#dashboard_instudio'

   resources :orders do 
      resources :categories, only: [:index ]
      get '/sizes', to: 'orders#sizes'
      get '/angles', to: 'orders#angles'
      get '/backgrounds', to: 'orders#backgrounds'
      get '/checkout', to: 'orders#checkout'
      get '/delivery', to: 'orders#delivery'

      resources :briefings, only: [ :new, :create, :index ]
      resources :deliveries, only: [ :new, :create, :index ]

    end 
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/background.rb
class Background < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :product, optional: true
  has_one_attached :photo
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  before_action :set_background, only: [ :show, :edit, :update, :destroy]

  def index
     @order = Order.find(params[:order_id])
    #  @category = Category.find(params[:category_id])
    @backgrounds = Background.all
  end

  def show
    @category = @background.category
  end

  def new
   
    @category = Category.find(params[:category_id])
    @background = Background.new
  end

  def edit
    # @category = Category.find(@background.category_id)
  end

  def create
    @background = Background.new(background_params)

    @background.category = Category.find(params[:category_id])


    
    if @background.save
      redirect_to categories_path, notice: "Your Background Product was successfully created."
    else
      render :new
    end
  end

  def update
   
    if @background.update(background_params)
      redirect_to category_path(@category), notice: "Your Background Product was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @background.destroy
    redirect_to root_path, notice: "Your Background Product was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_background
    @background = Background.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def background_params
    params.require(:background).permit(:bg_name,
                                :description,
                                :bg_color,
                                :photo
                                )
  end
end

app/views/backgrounds/edit.html.erb
<h1>Backgrounds#edit</h1>
<p>Find me in app/views/backgrounds/edit.html.erb</p>

app/views/backgrounds/index.html.erb
 

<div class="container">
    <% @backgrounds.each do |bg| %>

        <div class="card m-2" style="width: 18rem;">
                    <%= image_tag bg.photo, class: "card-img-top" %>

            <div class="card-body">
                <h5 class="card-title"> <%= bg.bg_name  %> </h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

                    <%= link_to order_path(@order, background_id: bg.id), method: :patch, class: "categories__list-btn btn-primary" do %>
                        Book a <%= bg.bg_name %>
                        <span class="fa-solid fa-arrow-right-long icon"></span>
                        <% end %>  
            </div>
        </div>
    <% end %>
</div>

app/views/backgrounds/new.html.erb
<br><br><br><br><br><br><br><br>
<div class="container">
  <h1>Background Registration </h1>

  <%= simple_form_for [ @category, @background ] do |f| %>
    <div class="row">
        <div class="col-4">
            <%= f.input :bg_name,
                        label: 'Background',
                        collection: ['NO Background', 'White Background', 'Colored Background' ]
                         %>
        </div>

        <div class="col-4">
            <%= f.input :bg_color,
                        label: 'HEX code Color' %>
         </div>

        <div class="col-4">
            <%= f.input :photo,
                        label: 'Upload an image',
                        as: :file %>
         </div>
        <div class="col-12">
            <%= f.input :description,
                        label: 'Description',
                        placeholder: '...' %>
         </div>

    <p><%= f.submit "Create Your Background Product", class: "btn btn-primary" %></p>
  <% end %>
</div>

app/views/backgrounds/show.html.erb
<h1>Backgrounds#show</h1>
<p>Find me in app/views/backgrounds/show.html.erb</p>