config/routes.rb
Rails.application.routes.draw do
 
  resources :instudios do 
  resources :moodboards, only: :index 
  resources :addons, only: :index 
  resources :calendars, only: [ :new, :create ]
  end

  resources :calendars
  resources :products
  resources :moodboards, only: [ :show, :edit, :update, :destroy, :index ]
  resources :addons, only: [ :show, :edit, :update, :destroy, :index ]

  resources :products do 
    resources :moodboards, only: [ :new, :create ]
    resources :addons, only: [ :new, :create, :index ]

  end

  resources :clients
  
  devise_for :users
  root to: "pages#home"

  resources :categories do 
    resources :backgrounds, only: [ :new, :create, :index ]
    resources :angles, only: [ :new, :create, :index ]
    resources :sizes, only: [ :new, :create, :index ]
   end
  
   resources :angles, only: [ :show, :edit, :update, :destroy ]
   resources :backgrounds, only: [ :show, :edit, :update, :destroy ]
   resources :sizes, only: [ :show, :edit, :update, :destroy ]
   resources :briefings, only: [ :show, :edit, :update, :destroy ]
   resources :deliveries, only: [ :show, :edit, :update, :destroy ]


   get '/profile', to: 'pages#profile'
   get '/new', to: 'pages#new'
   get '/dashboard', to: 'pages#dashboard'
   get '/dashboard_products', to: 'pages#dashboard_products'
   get '/dashboard_instudio', to: 'pages#dashboard_instudio'

   resources :orders do 
      resources :categories, only: [:index ]
      get '/sizes', to: 'orders#sizes'
      get '/angles', to: 'orders#angles'
      get '/backgrounds', to: 'orders#backgrounds'
      get '/checkout', to: 'orders#checkout'
      get '/delivery', to: 'orders#delivery'

      resources :briefings, only: [ :new, :create, :index ]
      resources :deliveries, only: [ :new, :create, :index ]

    end 
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_one :order
    has_one_attached :photo
    has_one :size
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [ :show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [ :show, :index ]

def index
      @categories = Category.all
end

def show
 
end

def new
  @category = Category.new
end

def edit
end

def create
  @category = Category.new(category_params)
  if @category.save
    redirect_to @category, notice: "Your Product Category was successfully created."
  else
    redirect_to new
  end
end

def update
  if @category.update(category_params)
    redirect_to @category, notice: "Your Product Category was successfully updated."
  else
    render :edit
  end
end

def destroy
  @category.destroy
  redirect_to root_path, notice: "Your Product Category  was successfully destroyed."
end

private

# Use callbacks to share common setup or constraints between actions.
def set_category
  @category = Category.find(params[:id])
end

# Only allow a trusted parameter "white list" through.
def category_params
  params.require(:category).permit(:category_name,
                              :description,
                              :photo
                              )
end
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
      <% @categories.each do |category| %>

<div class="card" style="width: 18rem;">
              <%= image_tag category.photo, class: "card-img-top" %>

  <div class="card-body">
    <h5 class="card-title"> <%= category.category_name  %> </h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

     <%= link_to orders_path(:user_id => current_user , :category_id => category.id), method: :post,  class: "btn btn-success" do %>
        Book a <%= category.category_name %>
        <span class="fa-solid fa-arrow-right-long icon"></span>
    <% end %>
<br>
    <%= link_to category_path(category), class: "btn btn-danger" do %>
        Edit <%= category.category_name %>
        <span class="fa-solid fa-arrow-right-long icon"></span>
    <% end %>
    <br>
    <%= link_to new_category_angle_path(:category_id => category.id), class: "btn btn-primary" do %>
        Create an Angle 
        <span class="fa-solid fa-arrow-right-long icon"></span>
    <% end %>

    <%= link_to new_category_background_path(:category_id => category.id), class: "btn btn-primary" do %>
        Create an Background 
        <span class="fa-solid fa-arrow-right-long icon"></span>
    <% end %>

      <%= link_to new_category_size_path(:category_id => category.id), class: "btn btn-primary" do %>
        Create a Size 
        <span class="fa-solid fa-arrow-right-long icon"></span>
    <% end %>
                    
  </div>
</div>


<% end %>

app/views/categories/new.html.erb
<br><br><br><br><br><br><br><br>
<div class="container">
  <h1>Product Category Registration </h1>

  <%= simple_form_for @category do |f| %>
    <div class="row">
        <div class="col-6">
            <%= f.input :category_name,
                        label: 'Product Category Name:',
                        collection: [ 'Baby Utensils',
                                      'Bags',
                                      'Children - LayFlat',
                                      'Clothing - LayFlat',
                                      'Clothing - Ghost', 
                                      'Cosmetics',
                                      'Electronics',
                                      'Glasses',
                                      'HomeTextil',
                                      'Jewelry',
                                      'kitchen gadgets',
                                      'Others',
                                      'Pets',
                                      'Shoes',
                                      'Tablewear'] %>
        </div>
      
        <div class="col-6">
            <%= f.input :photo,
                        label: 'Upload a banner',
                        as: :file %>
         </div>
        <div class="col-12">
            <%= f.input :description,
                        label: 'Description',
                        placeholder: '...' %>
         </div>

    <p><%= f.submit "Create Your Product Category ", class: "btn btn-primary" %></p>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>