config/routes.rb
Rails.application.routes.draw do
 
  resources :instudios do 
  resources :moodboards, only: :index 
  resources :addons, only: :index 
  resources :calendars, only: [ :new, :create ]
  end

  resources :calendars
  resources :products
  resources :moodboards, only: [ :show, :edit, :update, :destroy, :index ]
  resources :addons, only: [ :show, :edit, :update, :destroy, :index ]

  resources :products do 
    resources :moodboards, only: [ :new, :create ]
    resources :addons, only: [ :new, :create, :index ]

  end

  resources :clients
  
  devise_for :users
  root to: "pages#home"

  resources :categories do 
    resources :backgrounds, only: [ :new, :create, :index ]
    resources :angles, only: [ :new, :create, :index ]
    resources :sizes, only: [ :new, :create, :index ]
   end
  
   resources :angles, only: [ :show, :edit, :update, :destroy ]
   resources :backgrounds, only: [ :show, :edit, :update, :destroy ]
   resources :sizes, only: [ :show, :edit, :update, :destroy ]
   resources :briefings, only: [ :show, :edit, :update, :destroy ]
   resources :deliveries, only: [ :show, :edit, :update, :destroy ]


   get '/profile', to: 'pages#profile'
   get '/new', to: 'pages#new'
   get '/dashboard', to: 'pages#dashboard'
   get '/dashboard_products', to: 'pages#dashboard_products'
   get '/dashboard_instudio', to: 'pages#dashboard_instudio'

   resources :orders do 
      resources :categories, only: [:index ]
      get '/sizes', to: 'orders#sizes'
      get '/angles', to: 'orders#angles'
      get '/backgrounds', to: 'orders#backgrounds'
      get '/checkout', to: 'orders#checkout'
      get '/delivery', to: 'orders#delivery'

      resources :briefings, only: [ :new, :create, :index ]
      resources :deliveries, only: [ :new, :create, :index ]

    end 
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/instudio.rb
class Instudio < ApplicationRecord
  belongs_to :user

  belongs_to :product, optional: true
  belongs_to :moodboard, optional: true
  has_one :calendar, inverse_of: :instudio
  belongs_to :addon, optional: true
  belongs_to :client, optional: true
end

app/controllers/instudios_controller.rb
class InstudiosController < ApplicationController
  before_action :set_instudio, only: [ :show, :edit, :destroy, :background]

  def index
        @instudios = Instudio.all
  end

  def show   
  end   


  def addons
    @instudio = Instudio.find(params[:instudio_id])
    #  @category = Category.find(params[:category_id])
    @addons = Addon.all
  end

  def new
    @instudio = Instudio.new
  end

  def edit

  end

  def create
    @instudio = Instudio.new(instudio_params)
    @instudio.user = current_user 
    @product = @instudio.product 

    if @instudio.save
      redirect_to instudio_moodboards_path(@instudio), notice: "Your Order was successfully created."
    else  
      render :new
    end
  end


  def checkout
    @instudio = Instudio.find(params[:instudio_id])
    # @moodboards = Angle.where(:category_id == @category)
    # @briefing = Briefing.where(order_id: @order.id).last
    # @client = Client.where(user_id: current_user.id)
  end



  def update
    @instudio = Instudio.find(params[:id])
  
    if params[:addon_id].present?
      @instudio.update(instudio_params)
      redirect_to new_instudio_calendar_path(@instudio)
      
    elsif params[:moodboard_id].present?
      @instudio.update(instudio_params)
      redirect_to instudio_addons_path(@instudio)

    elsif params[:step].present?
      @instudio.update(instudio_params)
      redirect_to dashboard_path

    else
      render :new
        
      end
  end


  def destroy
    @instudio.destroy
    redirect_to root_path, notice: "Your Order was successfully destroyed."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_instudio
    @instudio = Instudio.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def instudio_params
    params.permit(:product_id, 
                                  :moodboard_id,
                                  :step,
                                  :addon_id,
                                  :calendar_id,
                                  :client_id )
  end


end

app/views/instudios/edit.html.erb
<br><br><br><br><br><br><br><br>
<div class="container">
  <h1>Instudio Registration </h1>
    <h1> <%= @instudio.product.product_name  %> </h1>

. 
 
 
 
 
 



  <%= simple_form_for @instudio do |f| %>
        <div class="row">
        <div class="col-6">
            <%= f.input :step,
                        label: 'STEP',
                        collection: ['Order pending ',
                                    'Order approved',
                                    'Product preparation',
                                    'Photographing',
                                    'In edit',
                                    'Re-edit',
                                    'Waiting for Client Aproval',
                                    'Waiting for Admin Aproval',
                                    'Project Done',
                                    'Ship back products' ] %>
        </div>
      


    <p><%= f.submit "Edit Your instudio ", class: "btn btn-primary" %></p>
  <% end %>
</div>

app/views/instudios/index.html.erb
<div class="container">
    <div class="card-group">
    <%= link_to categories_path do %>
        <div class="card" style="width: 18rem;">
        <img src="https://res.cloudinary.com/numama/image/upload/v1649685108/Eshoots/Screen_Shot_2022-04-11_at_10.51.39_gxuwfh.png" class="card-img-top" alt="...">
        <div class="card-body">
            <p class="card-text">MODEL SHOOT</p>
        </div>
        </div>
    <% end %>
    <%= link_to products_path do %>
        <div class="card" style="width: 18rem;">
            <img src="https://res.cloudinary.com/numama/image/upload/v1649685111/Eshoots/Screen_Shot_2022-04-11_at_10.49.10_ymbncu.png" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">LIFE STYLE</p>
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/instudios/new.html.erb
<h1>Instudio#new</h1>
<p>Find me in app/views/instudio/new.html.erb</p>

app/views/instudios/show.html.erb
<h1>Instudio#show</h1>
<p>Find me in app/views/instudio/show.html.erb</p>