config/routes.rb
Rails.application.routes.draw do
 
  resources :instudios do 
  resources :moodboards, only: :index 
  resources :addons, only: :index 
  resources :calendars, only: [ :new, :create ]
  end

  resources :calendars
  resources :products
  resources :moodboards, only: [ :show, :edit, :update, :destroy, :index ]
  resources :addons, only: [ :show, :edit, :update, :destroy, :index ]

  resources :products do 
    resources :moodboards, only: [ :new, :create ]
    resources :addons, only: [ :new, :create, :index ]

  end

  resources :clients
  
  devise_for :users
  root to: "pages#home"

  resources :categories do 
    resources :backgrounds, only: [ :new, :create, :index ]
    resources :angles, only: [ :new, :create, :index ]
    resources :sizes, only: [ :new, :create, :index ]
   end
  
   resources :angles, only: [ :show, :edit, :update, :destroy ]
   resources :backgrounds, only: [ :show, :edit, :update, :destroy ]
   resources :sizes, only: [ :show, :edit, :update, :destroy ]
   resources :briefings, only: [ :show, :edit, :update, :destroy ]
   resources :deliveries, only: [ :show, :edit, :update, :destroy ]


   get '/profile', to: 'pages#profile'
   get '/new', to: 'pages#new'
   get '/dashboard', to: 'pages#dashboard'
   get '/dashboard_products', to: 'pages#dashboard_products'
   get '/dashboard_instudio', to: 'pages#dashboard_instudio'

   resources :orders do 
      resources :categories, only: [:index ]
      get '/sizes', to: 'orders#sizes'
      get '/angles', to: 'orders#angles'
      get '/backgrounds', to: 'orders#backgrounds'
      get '/checkout', to: 'orders#checkout'
      get '/delivery', to: 'orders#delivery'

      resources :briefings, only: [ :new, :create, :index ]
      resources :deliveries, only: [ :new, :create, :index ]

    end 
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :photo

    has_one :moodboard
    has_one :addon
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [ :show, :index ]

def index
      @products = Product.all
end

def show
 
end

def new
  @product = Product.new
end

def edit
end

def create
  @product = Product.new(product_params)
  if @product.save
    redirect_to products_path,  notice: "Your Product  was successfully created."
  else
    redirect_to new
  end
end

def update
  if @product.update(product_params)
    redirect_to products_path, notice: "Your Product  was successfully updated."
  else
    render :edit
  end
end

def destroy
  @product.destroy
  redirect_to root_path, notice: "Your Product   was successfully destroyed."
end

private

# Use callbacks to share common setup or constraints between actions.
def set_product
  @product = Product.find(params[:id])
end

# Only allow a trusted parameter "white list" through.
def product_params
  params.require(:product).permit(:product_name,
                              :category_name,
                              :photo
                              )
end
end

app/views/products/edit.html.erb
<br><br><br><br><br><br><br><br>
<div class="container">
  <h1>Product Category Registration </h1>

  <%= simple_form_for @product do |f| %>
    <div class="row">
        <div class="col-6">
            <%= f.input :category_name,
                        label: 'Product Category Name:',
                        collection: [ 'Cosmetics',
                                      'Electronics',
                                      'Food & Beverages',
                                      'Jewerly',
                                      'Fashion',
                                      'Fashion - Baby',
                                      'Fashion - Assessories', 
                                      'Fashion - Shop the look', 
                                      'Homewear',
                                      'Homewear - Kitchen',
                                      'Homewear - Bathroom',
                                      'Homewear - Bedroom',
                                      'Homewear - Dining room'
                                      ] %>
        </div>

        <div class="col-6">
            <%= f.input :photo,
                        label: 'Upload a banner',
                        as: :file %>
         </div>

    <p><%= f.submit "Edit Your Product Category ", class: "btn btn-primary" %></p>
  <% end %>
</div>

app/views/products/index.html.erb
      <% @products.each do |product| %>

<div class="card" style="width: 18rem;">
              <%= image_tag product.photo, class: "card-img-top" %>

  <div class="card-body">
    <h5 class="card-title"> <%= product.category_name  %> </h5>

     <%= link_to instudios_path(:user_id => current_user , :product_id => product.id), method: :post,  class: "btn btn-success" do %>
        Book a <%= product.category_name %>
        <span class="fa-solid fa-arrow-right-long icon"></span>
    <% end %>
<br>
    <%= link_to edit_product_path(product), class: "btn btn-danger" do %>
        Edit <%= product.product_name %>
        <span class="fa-solid fa-arrow-right-long icon"></span>
    <% end %>
    <br>
    <%= link_to new_product_moodboard_path(:product_id => product.id), class: "btn btn-primary" do %>
        Create a Moodboard 
        <span class="fa-solid fa-arrow-right-long icon"></span>
    <% end %>

    <%= link_to new_product_addon_path(:product_id => product.id), class: "btn btn-primary" do %>
        Create an Add-On
        <span class="fa-solid fa-arrow-right-long icon"></span>
    <% end %>

      <%#= link_to new_category_size_path(:category_id => category.id), class: "btn btn-primary" do %>
        <%# Create a Size  %>
        <%# <span class="fa-solid fa-arrow-right-long icon"></span> %>
    <%# end %>
                    
  </div>
</div>


<% end %>

app/views/products/new.html.erb
<br><br><br><br><br><br><br><br>
<div class="container">
  <h1>Product Category Registration </h1>

  <%= simple_form_for @product do |f| %>
    <div class="row">
        <div class="col-6">
            <%= f.input :category_name,
                        label: 'Product Category Name:',
                        collection: [ 'Cosmetics',
                                      'Electronics',
                                      'Food & Beverages',
                                      'Jewerly',
                                      'Fashion',
                                      'Fashion - Baby',
                                      'Fashion - Assessories', 
                                      'Fashion - Shop the look', 
                                      'Homewear',
                                      'Homewear - Kitchen',
                                      'Homewear - Bathroom',
                                      'Homewear - Bedroom',
                                      'Homewear - Dining room'
                                      ] %>
        </div>

        <div class="col-6">
            <%= f.input :photo,
                        label: 'Upload a banner',
                        as: :file %>
         </div>

    <p><%= f.submit "Create Your Product Category ", class: "btn btn-primary" %></p>
  <% end %>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>